package com.ezc.hsil.webapp.model;
// Generated Sep 10, 2019 1:50:54 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EzcRequestDealers generated by hbm2java
 */
@Entity
@Table(name = "ezc_request_dealers", catalog = "hsil")
public class EzcRequestDealers implements java.io.Serializable {

	private Integer id;
	private EzcRequestHeader ezcRequestHeader;
	private String erdDealerCode;
	private String erdDealerName;

	public EzcRequestDealers() {
	}

	public EzcRequestDealers(EzcRequestHeader ezcRequestHeader, String erdDealerCode, String erdDealerName) {
		this.ezcRequestHeader = ezcRequestHeader;
		this.erdDealerCode = erdDealerCode;
		this.erdDealerName = erdDealerName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ERD_REQ_ID")
	public EzcRequestHeader getEzcRequestHeader() {
		return this.ezcRequestHeader;
	}

	public void setEzcRequestHeader(EzcRequestHeader ezcRequestHeader) {
		this.ezcRequestHeader = ezcRequestHeader;
	}

	@Column(name = "ERD_DEALER_CODE", length = 10)
	public String getErdDealerCode() {
		return this.erdDealerCode;
	}

	public void setErdDealerCode(String erdDealerCode) {
		this.erdDealerCode = erdDealerCode;
	}

	@Column(name = "ERD_DEALER_NAME", length = 45)
	public String getErdDealerName() {
		return this.erdDealerName;
	}

	public void setErdDealerName(String erdDealerName) {
		this.erdDealerName = erdDealerName;
	}

}
