package com.ezc.hsil.webapp.model;
// Generated Sep 10, 2019 2:12:43 PM by Hibernate Tools 5.2.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * EzcRequestHeader generated by hbm2java
 */
@Entity
@Table(name = "ezc_request_header", catalog = "hsil")
public class EzcRequestHeader implements java.io.Serializable {

	private int id;
	private String erhReqType;
	private String erhCreatedGroup;
	private String erhState;
	private String erhRequestedBy;
	private Date erhRequestedOn;
	private String erhStatus;
	private Date erhConductedOn;
	private String erhModifiedBy;
	private Date erhModifiedOn;
	private Integer erhNoOfAttendee;
	private Set<EzcRequestItems> ezcRequestItemses = new HashSet<EzcRequestItems>(0);

	public EzcRequestHeader() {
	}

	public EzcRequestHeader(int id) {
		this.id = id;
	}

	public EzcRequestHeader( String erhReqType, String erhCreatedGroup, String erhState, String erhRequestedBy,
			Date erhRequestedOn, String erhStatus, Date erhConductedOn, String erhModifiedBy, Date erhModifiedOn,
			Integer erhNoOfAttendee, Set<EzcRequestItems> ezcRequestItemses) {
		//this.id = id;
		this.erhReqType = erhReqType;
		this.erhCreatedGroup = erhCreatedGroup;
		this.erhState = erhState;
		this.erhRequestedBy = erhRequestedBy;
		this.erhRequestedOn = erhRequestedOn;
		this.erhStatus = erhStatus;
		this.erhConductedOn = erhConductedOn;
		this.erhModifiedBy = erhModifiedBy;
		this.erhModifiedOn = erhModifiedOn;
		this.erhNoOfAttendee = erhNoOfAttendee;
		this.ezcRequestItemses = ezcRequestItemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ERH_REQ_TYPE", length = 5)
	public String getErhReqType() {
		return this.erhReqType;
	}

	public void setErhReqType(String erhReqType) {
		this.erhReqType = erhReqType;
	}

	@Column(name = "ERH_CREATED_GROUP", length = 10)
	public String getErhCreatedGroup() {
		return this.erhCreatedGroup;
	}

	public void setErhCreatedGroup(String erhCreatedGroup) {
		this.erhCreatedGroup = erhCreatedGroup;
	}

	@Column(name = "ERH_STATE", length = 10)
	public String getErhState() {
		return this.erhState;
	}

	public void setErhState(String erhState) {
		this.erhState = erhState;
	}

	@Column(name = "ERH_REQUESTED_BY", length = 20)
	public String getErhRequestedBy() {
		return this.erhRequestedBy;
	}

	public void setErhRequestedBy(String erhRequestedBy) {
		this.erhRequestedBy = erhRequestedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ERH_REQUESTED_ON", length = 19)
	public Date getErhRequestedOn() {
		return this.erhRequestedOn;
	}

	public void setErhRequestedOn(Date erhRequestedOn) {
		this.erhRequestedOn = erhRequestedOn;
	}

	@Column(name = "ERH_STATUS", length = 10)
	public String getErhStatus() {
		return this.erhStatus;
	}

	public void setErhStatus(String erhStatus) {
		this.erhStatus = erhStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ERH_CONDUCTED_ON", length = 19)
	public Date getErhConductedOn() {
		return this.erhConductedOn;
	}

	public void setErhConductedOn(Date erhConductedOn) {
		this.erhConductedOn = erhConductedOn;
	}

	@Column(name = "ERH_MODIFIED_BY", length = 15)
	public String getErhModifiedBy() {
		return this.erhModifiedBy;
	}

	public void setErhModifiedBy(String erhModifiedBy) {
		this.erhModifiedBy = erhModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ERH_MODIFIED_ON", length = 19)
	public Date getErhModifiedOn() {
		return this.erhModifiedOn;
	}

	public void setErhModifiedOn(Date erhModifiedOn) {
		this.erhModifiedOn = erhModifiedOn;
	}

	@Column(name = "ERH_NO_OF_ATTENDEE")
	public Integer getErhNoOfAttendee() {
		return this.erhNoOfAttendee;
	}

	public void setErhNoOfAttendee(Integer erhNoOfAttendee) {
		this.erhNoOfAttendee = erhNoOfAttendee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ezcRequestHeader") 
	@Cascade({CascadeType.ALL})
	public Set<EzcRequestItems> getEzcRequestItemses() {
		return this.ezcRequestItemses;
	}

	public void setEzcRequestItemses(Set<EzcRequestItems> ezcRequestItemses) {
		this.ezcRequestItemses = ezcRequestItemses;
	}

}
