package com.ezc.hsil.webapp.model;
// Generated Sep 10, 2019 1:50:54 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * EzcRequestDealers generated by hbm2java
 */
@Entity
@Table(name = "ezc_request_dealers", catalog = "hsil")
public class EzcRequestDealers implements java.io.Serializable {

	private Integer id;
	private EzcRequestHeader ezcRequestHeader;
	private String erdDealerCode;
	private String erdDealerName;	
	private String erdMeetId;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date erdMeetDate;
	private Integer erdNoOfAttendee;
	private String erdInstructions;
	private String erdMeetStatus;
	private Double erdCostIncured;

	public EzcRequestDealers() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ERD_REQ_ID")
	public EzcRequestHeader getEzcRequestHeader() {
		return this.ezcRequestHeader;
	}

	public void setEzcRequestHeader(EzcRequestHeader ezcRequestHeader) {
		this.ezcRequestHeader = ezcRequestHeader;
	}
	@Column(name = "ERD_COST_INCURED")
	public Double getErdCostIncured() {
		return erdCostIncured;
	}

	public void setErdCostIncured(Double erdCostIncured) {
		this.erdCostIncured = erdCostIncured;
	}
	@Column(name = "ERD_DEALER_CODE", length = 10)
	public String getErdDealerCode() {
		return this.erdDealerCode;
	}

	public void setErdDealerCode(String erdDealerCode) {
		this.erdDealerCode = erdDealerCode;
	}

	@Column(name = "ERD_DEALER_NAME", length = 45)
	public String getErdDealerName() {
		return this.erdDealerName;
	}

	public void setErdDealerName(String erdDealerName) {
		this.erdDealerName = erdDealerName;
	}

	@Column(name = "ERD_MEET_ID", length = 10)
	public String getErdMeetId() {
		return erdMeetId;
	}

	public void setErdMeetId(String erdMeetId) {
		this.erdMeetId = erdMeetId;
	}

	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "ERD_MEET_DATE")
	public Date getErdMeetDate() {
		return erdMeetDate;
	}

	public void setErdMeetDate(Date erdMeetDate) {
		this.erdMeetDate = erdMeetDate;
	}

	@Column(name = "ERD_ATTENDANCE", length = 10)
	public Integer getErdNoOfAttendee() {
		return erdNoOfAttendee;
	}

	public void setErdNoOfAttendee(Integer erdNoOfAttendee) {
		this.erdNoOfAttendee = erdNoOfAttendee;
	}
	@Column(name = "ERD_INST", length = 100)
	public String getErdInstructions() {
		return erdInstructions;
	}
	
	public void setErdInstructions(String erdInstructions) {
		this.erdInstructions = erdInstructions;
	}

	@Column(name = "ERD_MEET_STS", length = 10)
	public String getErdMeetStatus() {
		return erdMeetStatus;
	}

	public void setErdMeetStatus(String erdMeetStatus) {
		this.erdMeetStatus = erdMeetStatus;
	}

	
}
