package com.ezc.hsil.webapp.model;
// Generated Sep 10, 2019 1:50:54 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EzcRetailerSales generated by hbm2java
 */
@Entity
@Table(name = "ezc_retailer_sales", catalog = "hsil")
public class EzcRetailerSales implements java.io.Serializable {

	private Integer id;
	private EzcRequestHeader ezcRequestHeader;
	private String ersBrand;
	private Double ersMonthlySales;
	private String ersMonthlyYearly;

	public EzcRetailerSales() {
	}

	public EzcRetailerSales(EzcRequestHeader ezcRequestHeader, String ersBrand, Double ersMonthlySales,
			String ersMonthlyYearly) {
		this.ezcRequestHeader = ezcRequestHeader;
		this.ersBrand = ersBrand;
		this.ersMonthlySales = ersMonthlySales;
		this.ersMonthlyYearly = ersMonthlyYearly;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ERS_REQ_ID")
	public EzcRequestHeader getEzcRequestHeader() {
		return this.ezcRequestHeader;
	}

	public void setEzcRequestHeader(EzcRequestHeader ezcRequestHeader) {
		this.ezcRequestHeader = ezcRequestHeader;
	}

	@Column(name = "ERS_BRAND", length = 45)
	public String getErsBrand() {
		return this.ersBrand;
	}

	public void setErsBrand(String ersBrand) {
		this.ersBrand = ersBrand;
	}

	@Column(name = "ERS_MONTHLY_SALES", precision = 22, scale = 0)
	public Double getErsMonthlySales() {
		return this.ersMonthlySales;
	}

	public void setErsMonthlySales(Double ersMonthlySales) {
		this.ersMonthlySales = ersMonthlySales;
	}

	@Column(name = "ERS_MONTHLY_YEARLY", length = 10)
	public String getErsMonthlyYearly() {
		return this.ersMonthlyYearly;
	}

	public void setErsMonthlyYearly(String ersMonthlyYearly) {
		this.ersMonthlyYearly = ersMonthlyYearly;
	}

}
